#!/usr/bin/env python3.7

#import re

import json

#def parseURL(apiURL):


def stripNone(readData):
        print(readData)


    for key, value in readData.items():
        if isinstance(readData, dict):
            return {key:stripNone(value) for key, value in readData.items() if key is not None and value is not None}
        else:
            yield "{}={}".format(key, value)



def parseFile(fileName):

    with open(fileName) as jsonData:
        readData = json.load(jsonData)
        #readData = json.dumps(f.read())
        #readData = json.loads("{0}".format(readData))
       # print(type(readData))
    #for key in readData:
    #   print("KEY:")
    #    print(key)

genList = list(stripNone(parseFile("dubai-submission-20180815.json")))
