#!/usr/bin/env python3.7

import praw
from datetime import datetime

reddit = praw.Reddit(
        user_agent = 'python3.7:personal_use_script:01 (by /u/apigban)',
        site_name = 'bot1'
        )

subreddit = reddit.subreddit('dubai')

posts_hot = subreddit.hot(limit=5)


def askDates():
    isValidDate1 = False
    isValidDate2 = False

    while not isValidDate1:
        year1 = input('Enter Year for Date 1  ')
        month1 = input('Enter Month for Date 1  ')
        day1 = input('Enter Day for Date 1  ')
        date1 = year1 + '|' + month1 + '|' + day1
        print(date1)
        date1 = datetime.strptime(date1, '%Y|%m|%d')
        validateDate(date1)
#       isValidDate1 = True
        print(f"Date 1 is {date1}.")


    while not isValidDate2:
        year2 = int(input('Enter Year'))
        month2 = int(input('Enter Month'))
        day2 = int(input('Enter Day'))
        date2 = datetime.date(year2, month2, day2)
#        date2 = datetime.strptime(date2, '%d|%m|%y')
#        isValidDate2 = True
        print(date2)

#    validateDates(date1,date2)

    return date1, date2

def validateDate(d):
    try:
        if len(d) == 10:
            datetime.strptime(d, '%Y|%m|%d')
            print(f'{d} is a valid date')
            return True
        else: return False

    except ValueError:
        return False

print(askDates())




#for submission in posts_hot:
#    print(submission.author.comments)
#    print(dir(submission.author.comments.top))
#    print(10 * '=')
