#!/usr/bin/env python3.7

import praw

reddit = praw.Reddit(client_id = 'NCfhYUhP-fGCBw',
                      client_secret = 'xy1trVfcAjKJuZ3hD3nJ5mhH2qM',
                      username = 'senti_bot_apigban',
                      password = 'wuZRuv4XwpyLcYVizt3H',
                      user_agent = 'python3.7:personal_use_script:01 (by /u/apigban)'
                      )

subreddit = reddit.subreddit('dubai')

hot_python = subreddit.hot(limit=3)

for submission in hot_python:
    if not submission.stickied:
        print('Title: {}, ups: {}, downs: {}, Have we visited: {}'.format(
                submission.title,
                submission.ups,
                submission.downs,
                submission.visited
                )
            )

        comments = submission.comments.replace_more(limit=0)
        for comment in comments.list():
            print(10*'-')
            print('Parent ID:', comment.parent())
            print('Comment.ID', comment.id)
            print(comment.body)
