#!/usr/bin/env python3.7

from psaw import PushshiftAPI
from getInfo import fetchInput


psapi = PushshiftAPI()


argList = fetchInput()

results = list(psapi.search_submissions(
    subreddit = argList[0],
    initial = argList[2],
    final = argList[3],
    limit = argList[4]
    )
    )

print(results)
