#!/usr/bin/env python3.7

import praw


reddit = praw.Reddit(client_id = 'NCfhYUhP-fGCBw',
                      client_secret = 'xy1trVfcAjKJuZ3hD3nJ5mhH2qM',
                      username = 'senti_bot_apigban',
                      password = 'wuZRuv4XwpyLcYVizt3H',
                      user_agent = 'python3.7:personal_use_script:01 (by /u/apigban)'
                      )

subreddit = reddit.subreddit('dubai')

posts_hot = subreddit.hot(limit=5)

for submission in posts_hot:
    print(dir(submission))
