#!/usr/bin/env python3.7

import praw

reddit = praw.Reddit(
         user_agent = 'python3.7:personal_use_script:01 (by /u/apigban)',
         site_name = 'bot1'
         )

subreddit = reddit.subreddit('dubai')

hot_python = subreddit.hot(limit=3)

for submission in hot_python:
    if not submission.stickied:
        print('Title: {}, ups: {}, downs: {}, Have we visited: {}'.format(
                submission.title,
                submission.ups,
                submission.downs,
                submission.visited
                )
            )

        comments = submission.comments.replace_more(limit=0)
        for comment in comments.list():
            print(10*'-')
            print('Parent ID:', comment.parent())
            print('Comment.ID', comment.id)
            print(comment.body)
