#!/usr/bin/env python3.7

import praw

reddit = praw.Reddit(
        user_agent = 'python3.7:personal_use_script:01 (by /u/apigban)',
        site_name = 'bot1'
        )

subreddit = reddit.subreddit('dubai')

for comment in subreddit.stream.comments():
    try:
        parent_id = str(comment.parent())

        original = reddit.comment(parent_id)
        print('Parent:')
        print(original.body)

        print('Reply:')
        print(comment.body)

    except praw.exceptions.PRAWException as e:
        pass
